### ISSUE TITLE
I am unable to run it on command line after reaching to How many tickets you want to book?

### ISSUE THREAD

**Issue by JayeshWani7** [Harshit1q1/Airline-Ticket-Reservation-System#1]
I get error Exception in thread "main" java.util.NoSuchElementException
        at java.base/java.util.Scanner.throwFor(Scanner.java:945)
        at java.base/java.util.Scanner.next(Scanner.java:1602)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2267)
        at java.base/java.util.Scanner.nextInt(Scanner.java:2221)
        at AirlineTicketReservationSystem.main(AirlineTicketReservationSystem.java:201)

**Comment by Harshit1q1** [comment]
Hi Jayesh, Thank you for reporting the issue. I will look further into the issue.

**Comment by JayeshWani7** [comment]
Have you got any errors?

**Comment by Harshit1q1** [comment]
I am able to reproduce the same error as you have mentioned and working on the issue resolution.

**Comment by Harshit1q1** [comment]
I have updated the code and now I am able to run the program without encountering any error.

**Comment by JayeshWani7** [comment]
Yeah the code works properly now
